### ISSUE TITLE
USER STORY: set up repository

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#1]
EPIC1: set up repo

As a **developer** I can **set up a new workspace** so that **I can start working on my project**

## Acceptance Criteria
* Acceptance Criteria 1: a repository in Github
* Acceptance Criteria 2: an IDE to work in
* Acceptance Criteria 3: a project board
* Acceptance Criteria 4: readme & testing files

## Tasks
- [x] Task 1: Create a github repository with initial README and TESTING files
- [x] Task 2: Set up env, venv in VS Code and Gitpod
- [x] Task 3: Install Django
- [x] Task 4: Create project board, issues, labels, epics and milestones
