### ISSUE TITLE
USER STORY: tutorial description

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#10]
EPIC 2: Build core website for basic interaction

As a **site user** I can **click on each tutorial listing** so that **I can read more information about the tutorial.**

## Acceptance Criteria
* Acceptance Criteria 1: A call to action button is present to access each listing
* Acceptance Criteria 2: A new page with tutorial information is loaded
* Acceptance Criteria 3: A call to action button to register/login or book a tutorial is visible

## Tasks
- [x] Task 1: Create a Tutorial detail page template
- [x] Task 2: Show individual tutorial’s information
- [x] Task 3: Add a call to action button for registering/booking for the tutorial
