### ISSUE TITLE
USER STORY: book a tutorial

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#11]
EPIC 4: User can view, book tutorials and manage their bookings

As a **site user** I can **book a tutorial** so that **I can attend it.**

## Acceptance Criteria
* Acceptance Criteria 1: The “book a tutorial” button visible in the tutorial description page
* Acceptance Criteria 2: the user can select specific time & date of the tutorial from a calendar view.
* Acceptance Criteria 3: lapsed or booked tutorial warning is shown upon activation.
* Acceptance Criteria 4: a new page opens upon clicking on calendar event
* Acceptance Criteria 5: a confirmation modal is visible upon clicking "Book tutorial" button
* Acceptance Criteria 6: a confirmation message is displayed and redirection to My Tutorials page is activated

## Tasks
- [x] Task 1: add a “Book tutorial” button to each description page
- [x] Task 2: imlement a calendar view using Full Calendar
- [x] Task 3: implement modals for lapsed/booked tutorials
- [x] Task 4: create a new tutorial page template
- [x] Task 5: add a confirmation modal
- [x] Task 6: show confirmation message for successful booking
- [x] Task 7: add redirection to My Tutorials page
