### ISSUE TITLE
USER STORY: My Tutorials page

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#12]
EPIC 4: User CRUD

As a **site user** I can **go to Tutorials page** so that **I can manage them.**

## Acceptance Criteria
* Acceptance Criteria 1: “My Tutorials” link is visible in the navbar upon user login.
* Acceptance Criteria 2: a list of all past and upcoming bookings appears in a new page.
* Acceptance Criteria 3: a call to action button is visible if no bookings are made.

## Tasks
- [x] Task 1: create a My Tutorials template.
- [x] Task 2: generate list of past and future tutorial bookings.
- [x] Task 3: if there are no bookings, add call to action buttons for "View tutorial list"/"Book tutorial" .
- [x] Task 4: write code to redirect to the tutorial booking page.
