### ISSUE TITLE
USER STORY: edit the booking

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#13]
EPIC: User can view, book tutorials and manage their bookings

As a **site user** I can **edit my booking** so that **I can adjust the details if I change my mind.**

## Acceptance Criteria
* Acceptance Criteria 1: given the user is logged in, the edit button is visible next to each future booking in the My Tutorials page
* Acceptance Criteria 2: upon clicking the edit button, a new page loads with a drop down form allowing the user to select a new booking
* Acceptance Criteria 3: a call to action button "Submit booking" is visible on the form page
* Acceptance Criteria 4: user is redirected to the My Tutorials page
* Acceptance Criteria 5: a confirmation message is displayed after the booking is edited

## Tasks
- [x] Task 1: create an edit booking button
- [x] Task 2: create a link to the new page
- [x] Task 3: create an Edit Booking template for displaying a form with available tutorial dates/times 
- [x] Task 4: implement a confirmation message for successful edit
- [x] Task 5: implement redirection to My Tutorials page
