### ISSUE TITLE
USER STORY: custom tutorial

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#14]
EPIC 7: future feature development

As a **site user** I can **submit a request for a customised tutorial** so that **I can have a lesson based on my individual needs.**

## Acceptance Criteria
* Acceptance Criteria 1: Given the user is logged in, a “Request a Custom Tutorial” button is visible within the tutorial list page
* Acceptance Criteria 2: When clicked, a form containing Name, Contact Email, Date & Title of Tutrial and a Text Area appears
* Acceptance Criteria 3: A "Submit" button is visible below the form
* Acceptance Criteria 4: Upon submission a confirmation message is displayed
* Acceptance Criteria 5: If any required fields are missing, a warning message is displayed
* Acceptance Criteria 6: The form resets or refreshes after successful submission

- [ ] Task 1: Create a form using Django crispy forms to include the fields for Name, Contact Email, Date, Title, and Text Area
- [ ] Task 2: Implement appropriate warning messages displayed if the user misses any information.
- [ ] Task 3: Enable a confirmation message to appear upon successful form submission.
- [ ] Task 4: Ensure that the form fields are cleared upon successful submission.
