### ISSUE TITLE
USER STORY: comment & leave a review

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#15]
EPIC: future features

As a **site user** I can **comment on the tutorial** so that **I can share my feedback**

## Acceptance Criteria
* Acceptance Criteria 1: Given the user is logged in, Review form is available on the tutorial detail page after a user completes the tutorial
* Acceptance Criteria 2: a confirmation message is displayed upon submission
* Acceptance Criteria 3: the review is visible under respective tutorial showing the username, star rating and review text
* Acceptance Criteria 4: the review is only available to the users that participated in the tutorial
* Acceptance Criteria 5:  site admin can approve or remove reviews

- [ ] Task 1: create a review model
- [ ] Task 2: use crispy forms to display at the front end
- [ ] Task 3: add form validation for mandatory fields
- [ ] Task 4: enable user authorisation for review submission
- [ ] Task 5:  add a confirmation message upon successful review submission
