### ISSUE TITLE
USER STORY: set up required apps and database

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#17]
EPIC 1: Set up the project and project board

As a **developer** I can **set up required apps and a database** so that **I can manage data and start building the application**.

## Acceptance Criteria
* Acceptance Criteria 1: The PostgreSQL from Code Institute database is created
* Acceptance Criteria 2: Relevant apps are created (home, tutorial, dashboard)
* Acceptance Criteria 3: Database tables created for use

## Tasks
- [x] Task 1: Create CI PostgreSQL database
- [x] Task 2: Install apps and create urls.py file(s)
- [x] Task 3: Create Tutorial, TutorialDate and Booking models and migrate them
