### ISSUE TITLE
USER STORY: deploy the project to Heroku

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#18]
EPIC 1: Set up the project and project board

As a **developer** I can **deploy the project to Heroku** so that it is **accessible online**.

## Acceptance Criteria
* Acceptance Criteria 1: Environment variables are configured and hidden
* Acceptance Criteria 2: The project is deployed

## Tasks
- [ ] Task 1: Install gunicorn and whitenoise
- [ ] Task 2: Push the project to Github repository
- [ ] Task 3: Deploy to Heroku
- [ ] Task 4: Check the deployed app is working
