### ISSUE TITLE
USER STORY: Manage tutorial information

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#2]
EPIC: <epic>

As a **site admin** I can ** access the admin site** so that **I can manage the bookings and edit tutorial information**

## Acceptance Criteria
* Acceptance Criteria 1: log in with a username/email and a password.
* Acceptance Criteria 2: if error typing during the log in - display an error.
* Acceptance Criteria 3: admin can see a list of bookings and can access each entry to edit the content.
* Acceptance Criteria 4: Admin can create/edit/delete new/existing tutorials

## Tasks
- [x] Task 1: create a superuser
- [x] Task 2: implement CRUD functionality
- [x] Task 3: create models for tutorial bookings
