### ISSUE TITLE
USER STORY: apply design

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#20]
EPIC: <epic>

As a **developer** I can **apply design of choice** so that **the website is visually appealing and represents the purpose**

## Acceptance Criteria
* Acceptance Criteria 1: Design layout is implemented
* Acceptance Criteria 2: Font and colour scheme are implemented

## Tasks
- [ ] Task 1: Choose Bootstrap design style 
- [ ] Task 2: Choose font 
- [ ] Task 3: Choose colour palette
