### ISSUE TITLE
USER STORY: cancel booking

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#21]
EPIC 4: User can view, book tutorials and manage their bookings

As a **site user** I can **cancel my booking** so that **I can adjust the details if I change my mind.**

## Acceptance Criteria
* Acceptance Criteria 1: given the user is logged in, the cancel booking button is visible next to each future booking in the My Tutorials page
* Acceptance Criteria 2: upon clicking the cancel booking button a confirmation modal appears
* Acceptance Criteria 3: a call to action "cancel booking" button is visible
* Acceptance Criteria 4: user is redirected to the My Tutorials page
* Acceptance Criteria 5: a confirmation message is displayed after the booking is cancelled

## Tasks
- [x] Task 1: create a cancel booking button
- [x] Task 2: create a modal using Bootstrap 5
- [x] Task 3: implement a successful cancellation message
- [x] Task 4: implement redirection to My Tutorials page
