### ISSUE TITLE
USER STORY: access admin login on website

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#22]
EPIC 5: Site admin can manage the information in the front end

As a **site admin** I can **access the front end admin site** so that I can **access content available for site admin only.**

## Acceptance Criteria
* Acceptance Criteria 1: log in with a username and password
* Acceptance Criteria 2: after login the site admin's name is visible in the navbar
* Acceptance Criteria 3: a Dashboard page is displayed in the navbar
* Acceptance Criteria 4: a new page displaying add, edit, delete Tutorials and bookings is visible.

## Tasks
- [x] Task 1: create a template for the dashboard
- [x] Task 2: set up redirection the the home page upon successful login
- [x] Task 3: display confirmation message upon login/logout
