### ISSUE TITLE
USER STORY: add new tutorials and tutorial dates/times

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#23]
EPIC 5: Site admin front end CRUD

As a **site admin** I can **create new Tutorials and tutorial dates & times** so that I can **offer the user different content**.

## Acceptance Criteria
* Acceptance Criteria 1: a call to action buttons to add new tutorials and tutorial dates & times are visible in the Dashboard
* Acceptance Criteria 2: a new page rendering a form with appropriate fields is visible 
* Acceptance Criteria 3: a successful submission message is visible
* Acceptance Criteria 4: an error message displayed if any fields are missing
* Acceptance Criteria 5: the user is redirected to the main dashboard

## Tasks
- [x] Task 1: create a "Add" button and enable a hyperlink 
- [x] Task 2: create an Add Tutorial and Add Tutorial date & time pages' templates
- [x] Task 3: install crispy forms
- [x] Task 4: enable redirection
- [x] Task 5: enable confirmation messages
- [ ] Task 6: add code to validate form submission
- [ ] Task 7: enable error message if a required field is missing
