### ISSUE TITLE
USER STORY: delete Tutorials and Bookings

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#24]
EPIC 5: Site admin front end CRUD

As a **site admin** I can **delete Tutorials, tutorial dates/times and bookings** so that I can **update the content**.

## Acceptance Criteria
* Acceptance Criteria 1: a call to action button to delete new tutorials is visible in the Dashboard
* Acceptance Criteria 2: a confirmation modal is visible  
* Acceptance Criteria 3: a successful submission message is visible
* Acceptance Criteria 5: the site admin is redirected to the main dashboard
* Acceptance Criteria 6: the regular user is notified about the cancellation

## Tasks
- [ ] Task 1: create a "Delete" button and enable a hyperlink 
- [ ] Task 2: create a modal using Bootstrap 5
- [ ] Task 4: enable redirection
- [ ] Task 5: enable confirmation message
- [ ] Task 6: enable email confirmation using JS library
