### ISSUE TITLE
USER STORY: website validation

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#25]
EPIC 6: website testing & validation

As a **developer**, I can **validate each page and app** so that **I know that the code adheres to best practices.**

## Acceptance Criteria
* Acceptance Criteria 1: Html pages are validated with no critical issues
* Acceptance Criteria 2: CSS pages are validated with no critical issues
* Acceptance Criteria 3: JS pages are validated with no critical issues
* Acceptance Criteria 4: Python pages are validated with no critical issues

## Tasks
- [x] Task 1: Check each html page against W3C html validator
- [x] Task 2: Check each css file against W3C CSS validator
- [x] Task 3: Check each python file against CI Pep8 validator
- [x] Task 4: Check each JS file against JSlinter validator
- [x] Task 5: Document any major validation errors in the TESTING.md
