### ISSUE TITLE
USER STORY: Home page

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#3]
EPIC: Build core website for no registration needs

As a **site user** I can **view the home page of the website** so that **I can understand and see the purpose of it.**

## Acceptance Criteria
* Acceptance Criteria 1: visually appealing display and layout
* Acceptance Criteria 2: the brand & purpose of the website is obvious
* Acceptance Criteria 3: call to action button for tutorial list is visible 

## Tasks
- [x] Task 1: create home page template in HTML/CSS
- [x] Task 2: write a blurb that defined the website's purpose
- [x] Task 3: add and implement functionality for call to action button
