### ISSUE TITLE
USER STORY: maintain README and TESTING files

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#30]
EPIC 6: website testing & validation

As a **developer**, I can **note the website progression in the README** so that **anyone can see the steps and actions taken for the release of the website.**

## Acceptance Criteria
* Acceptance Criteria 1: Readme.md file is updated throughout the progression of the project
* Acceptance Criteria 2: TESTING.md file is updated with any changes and major bugs

## Tasks
- [ ] Task 1: Record project scope and technologies used in the README.md
- [ ] Task 2: Record any resources and tools used for testing, validation and deployment
- [ ] Task 3: Have a section about deployment, cloning and forking the repository
- [ ] Task 4: Include the deployed site’s website in the README.md
- [ ] Task 5: Log design choices and changes in the README.md
