### ISSUE TITLE
USER STORY: add keywords

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#31]
EPIC 2: core website functionality

As a **developer** I can **add main website keywords and description** so that **the website gains higher searchability in the search engines.**

## Acceptance Criteria
* Acceptance Criteria 1: the website browser tab is named appropriatelly
* Acceptance Criteria 2: keywords for search engines are identified

## Tasks
- [x] Task 1: Edit the title tag in base template
- [x] Task 2: add keywords in the head tag 
- [x] Task 3: add description in the head tag
