### ISSUE TITLE
USER STORY: About page

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#4]
EPIC 2: Build core website for basic interaction

As a **site user** I can **view the About page** so that **I can read more about the website’s owner**

## Acceptance Criteria
* Acceptance Criteria 1: image of the owner is present on the page
* Acceptance Criteria 2: a description/story of the site owner is present
* Acceptance Criteria 3: a call to action button is visible directing to the tutorials’ list page

## Tasks
- [x] Task 1: set up an about page template
- [x] Task 2: upload a profile image
- [x] Task 3: write a description about the site owner
- [x] Task 4: create a hyperlink to the button directing to the tutorial list page
