### ISSUE TITLE
USER STORY: Header

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#5]
EPIC 2: Build core website for basic interaction

As a **site user** I can **see the header** so that **I can access different pages from one place.**

## Acceptance Criteria
* Acceptance Criteria 1: The logo & the website name is visible
* Acceptance Criteria 2: The main navigation menu is present

## Tasks
- [x] Task 1: create the header template for the website
- [x] Task 2: add the logo/website name to the header
- [x] Task 3: set up navigation links to Home, About, Tutorial List, Register and Login pages
