### ISSUE TITLE
USER STORY: Footer

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#6]
EPIC 2: Build core website for basic interaction

As a **site user** I can **see the footer** so that **I can access the social media and contact information.**

## Acceptance Criteria
* Acceptance Criteria 1: the social media and contact information is present
* Acceptance Criteria 2: the logo/website names are visible 

## Tasks
- [x] Task 1: create a template for the footer
- [x] Task 2: create hyperlinks for each platform
- [x] Task 3: use fontawesome for icons
