### ISSUE TITLE
USER STORY: create an account

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#8]
EPIC 3: User can login/register for an account

As a **first time user** I can **create an account** so that **I can sign in and acces member's features.**

## Acceptance Criteria
* Acceptance Criteria 1: a Register button visible in the navigation bar and takes the user to the registration page
* Acceptance Criteria 2: the user can register with a valid username and password
* Acceptance Criteria 3: If the user enters incorrect information, an error message is displayed
* Acceptance Criteria 4: a registration message is displayed 

## Tasks
- [x] Task 1: install Django allauth and edit prepopulated register/login/logout templates
- [x] Task 2: redirect user to the main page after logging in
- [x] Task 3: create access restrictions
- [x] Task 4: display a successful register/logout message
