### ISSUE TITLE
USER STORY: Login & logout

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides-pp4#9]
EPIC 3: User can login/register for an account

As a **site user** I can **login to & logout of the website** so that **I can access and manage my content.**

## Acceptance Criteria
* Acceptance Criteria 1: log in button is visible in the navigation bar and redirects to the login page
* Acceptance Criteria 2: user can login using their username and password
* Acceptance Criteria 3: the username is visible in the nav bar indicating that the user is logged in
* Acceptance Criteria 4: logout button is visible in the navbar upon successful log in
* Acceptance Criteria 5: a confirmation message appears when the user is loged in
* Acceptance Criteria 6: a logout confirmation prompt is visible

## Tasks
- [x] Task 1: display error messages if login input is incorrect
- [x] Task 2: display user’s name in the navbar 
- [x] Task 3: set up redirection to the home page after logging in/out.
